# Generated by Django 6.0.8 on 2026-08-05 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('CONTRATACION', 'Contratación'), ('RRHH', 'Recursos Humanos'), ('PSICOLOGIA', 'Psicología'), ('SEGURIDAD', 'Seguridad ocupacional'), ('ADMIN', 'Administrador / Gerente')], default='ADMIN', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcesoSeleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=120)),
                ('cedula', models.CharField(max_length=30, unique=True, verbose_name='número de cédula')),
                ('celular', models.CharField(max_length=30, verbose_name='número de celular')),
                ('fecha_llegada', models.DateField(verbose_name='fecha de llegada de la hoja de vida')),
                ('vacante', models.CharField(max_length=150, verbose_name='vacante o área')),
                ('etapa_actual', models.CharField(choices=[('RRHH', 'RRHH'), ('PSICOLOGIA', 'Psicología'), ('SEGURIDAD', 'Seguridad ocupacional'), ('CONTRATACION', 'Contratación')], default='RRHH', max_length=20)),
                ('estado', models.CharField(choices=[('EN_CURSO', 'En curso'), ('LISTO_CONTRATACION', 'Listo para contratación'), ('CONTRATADO', 'Contratado'), ('RECHAZADO', 'Rechazado')], default='EN_CURSO', max_length=25)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'proceso de selección',
                'verbose_name_plural': 'procesos de selección',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('RRHH', 'RRHH'), ('PSICOLOGIA', 'Psicología'), ('SEGURIDAD', 'Seguridad ocupacional'), ('CONTRATACION', 'Contratación')], max_length=20)),
                ('resultado', models.CharField(choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], max_length=12)),
                ('observacion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('decidido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisiones', to=settings.AUTH_USER_MODEL)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisiones', to='procesos.procesoseleccion')),
            ],
            options={
                'ordering': ['fecha'],
                'constraints': [models.UniqueConstraint(fields=('proceso', 'etapa'), name='una_decision_por_etapa')],
            },
        ),
    ]
