# Generated by Django 6.0.8 on 2026-08-06 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0003_bloqueo_acceso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoseleccion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='procesoseleccion',
            name='archivado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procesoseleccion',
            name='archivado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procesos_archivados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='decision',
            name='etapa',
            field=models.CharField(choices=[('RRHH', 'Talento Humano'), ('PSICOLOGIA', 'Psicología'), ('SEGURIDAD', 'Seguridad y Salud en el Trabajo'), ('CONTRATACION', 'Contratación')], max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('SIN_ASIGNAR', 'Sin acceso asignado'), ('CONTRATACION', 'Contratación'), ('RRHH', 'Talento Humano'), ('PSICOLOGIA', 'Psicología'), ('SEGURIDAD', 'Seguridad y Salud en el Trabajo'), ('GERENTE', 'Gerente')], default='SIN_ASIGNAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='procesoseleccion',
            name='etapa_actual',
            field=models.CharField(choices=[('RRHH', 'Talento Humano'), ('PSICOLOGIA', 'Psicología'), ('SEGURIDAD', 'Seguridad y Salud en el Trabajo'), ('CONTRATACION', 'Contratación')], default='RRHH', max_length=20),
        ),
        migrations.CreateModel(
            name='CambioGerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato_nombre', models.CharField(max_length=221)),
                ('cedula', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('ACTUALIZACION', 'Actualización'), ('ARCHIVADO', 'Desactivación'), ('RESTAURADO', 'Restauración'), ('ELIMINADO', 'Eliminación definitiva')], max_length=20)),
                ('descripcion', models.TextField()),
                ('etapa_anterior', models.CharField(blank=True, choices=[('RRHH', 'Talento Humano'), ('PSICOLOGIA', 'Psicología'), ('SEGURIDAD', 'Seguridad y Salud en el Trabajo'), ('CONTRATACION', 'Contratación')], max_length=20)),
                ('etapa_nueva', models.CharField(blank=True, choices=[('RRHH', 'Talento Humano'), ('PSICOLOGIA', 'Psicología'), ('SEGURIDAD', 'Seguridad y Salud en el Trabajo'), ('CONTRATACION', 'Contratación')], max_length=20)),
                ('estado_anterior', models.CharField(blank=True, choices=[('EN_CURSO', 'En curso'), ('LISTO_CONTRATACION', 'Listo para contratación'), ('CONTRATADO', 'Contratado'), ('RECHAZADO', 'Rechazado')], max_length=25)),
                ('estado_nuevo', models.CharField(blank=True, choices=[('EN_CURSO', 'En curso'), ('LISTO_CONTRATACION', 'Listo para contratación'), ('CONTRATADO', 'Contratado'), ('RECHAZADO', 'Rechazado')], max_length=25)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_gerencia', to='procesos.procesoseleccion')),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_gerencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
