# Generated by Django 6.0.8 on 2026-08-06 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0004_procesoseleccion_activo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='decision',
            name='una_decision_por_etapa',
        ),
        migrations.AddField(
            model_name='decision',
            name='anulada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decision',
            name='anulada_por_gerencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisiones_anuladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decision',
            name='vigente',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='decision',
            constraint=models.UniqueConstraint(condition=models.Q(('vigente', True)), fields=('proceso', 'etapa'), name='una_decision_vigente_por_etapa'),
        ),
    ]
