# Generated by Django 6.0.8 on 2026-08-06 17:44

import django.db.models.deletion
from datetime import timedelta
from django.conf import settings
from django.db import migrations, models


PLAZOS = {"RRHH": 2, "PSICOLOGIA": 3, "SEGURIDAD": 6, "CONTRATACION": 2}


def crear_seguimientos_existentes(apps, schema_editor):
    Proceso = apps.get_model("procesos", "ProcesoSeleccion")
    Seguimiento = apps.get_model("procesos", "SeguimientoEtapa")
    for proceso in Proceso.objects.all().iterator():
        inicio = proceso.creado_en
        ciclos = {}
        decisiones = proceso.decisiones.filter(vigente=True).order_by("fecha")
        for decision in decisiones:
            ciclos[decision.etapa] = ciclos.get(decision.etapa, 0) + 1
            Seguimiento.objects.create(
                proceso_id=proceso.pk,
                etapa=decision.etapa,
                ciclo=ciclos[decision.etapa],
                inicio=inicio,
                fecha_limite=inicio + timedelta(days=PLAZOS[decision.etapa]),
                fin=decision.fecha,
                resultado=decision.resultado,
                cerrado_por_id=decision.decidido_por_id,
            )
            inicio = decision.fecha
        if proceso.activo and proceso.estado not in ("RECHAZADO", "CONTRATADO"):
            ciclos[proceso.etapa_actual] = ciclos.get(proceso.etapa_actual, 0) + 1
            Seguimiento.objects.create(
                proceso_id=proceso.pk,
                etapa=proceso.etapa_actual,
                ciclo=ciclos[proceso.etapa_actual],
                inicio=inicio,
                fecha_limite=inicio + timedelta(days=PLAZOS[proceso.etapa_actual]),
            )


def borrar_seguimientos(apps, schema_editor):
    apps.get_model("procesos", "SeguimientoEtapa").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0005_remove_decision_una_decision_por_etapa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('RRHH', 'Talento Humano'), ('PSICOLOGIA', 'Psicología'), ('SEGURIDAD', 'Seguridad y Salud en el Trabajo'), ('CONTRATACION', 'Contratación')], max_length=20)),
                ('ciclo', models.PositiveSmallIntegerField(default=1)),
                ('inicio', models.DateTimeField()),
                ('fecha_limite', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('resultado', models.CharField(blank=True, choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('AJUSTADO', 'Ajustado por Gerencia')], max_length=12)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos_cerrados', to=settings.AUTH_USER_MODEL)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='procesos.procesoseleccion')),
            ],
            options={
                'ordering': ['inicio'],
                'constraints': [models.UniqueConstraint(fields=('proceso', 'etapa', 'ciclo'), name='un_ciclo_por_etapa_proceso')],
            },
        ),
        migrations.RunPython(crear_seguimientos_existentes, borrar_seguimientos),
    ]
