# Generated by Django 6.0.8 on 2026-08-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0006_seguimientoetapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientoetapa',
            name='segundos_pausados',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
