# Generated by Django 6.0.8 on 2026-08-08 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0008_recalcular_plazos_habiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LOGIN_OK', 'Inicio de sesión correcto'), ('LOGIN_FAIL', 'Inicio de sesión fallido'), ('ACCOUNT_LOCK', 'Cuenta bloqueada'), ('ACCESS_DENIED', 'Acceso denegado'), ('USER_CREATED', 'Usuario creado'), ('USER_UPDATED', 'Usuario editado'), ('PASSWORD_CHANGED', 'Contraseña cambiada')], max_length=24)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('identificador_hash', models.CharField(blank=True, max_length=64)),
                ('detalle', models.CharField(blank=True, max_length=250)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('SIN_ASIGNAR', 'Sin acceso asignado'), ('CONTRATACION', 'Contratación'), ('RRHH', 'Talento Humano'), ('PSICOLOGIA', 'Psicología'), ('SEGURIDAD', 'Seguridad y Salud en el Trabajo'), ('GERENTE', 'Gerente')], db_index=True, default='SIN_ASIGNAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='procesoseleccion',
            name='cedula',
            field=models.CharField(db_index=True, max_length=30, verbose_name='número de cédula'),
        ),
        migrations.AddIndex(
            model_name='procesoseleccion',
            index=models.Index(fields=['activo', 'estado', 'etapa_actual'], name='proceso_flujo_idx'),
        ),
        migrations.AddIndex(
            model_name='procesoseleccion',
            index=models.Index(fields=['fecha_llegada'], name='proceso_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='seguimientoetapa',
            index=models.Index(fields=['fin', 'fecha_limite'], name='seguimiento_plazo_idx'),
        ),
        migrations.AddIndex(
            model_name='seguimientoetapa',
            index=models.Index(fields=['etapa', 'fin'], name='seguimiento_etapa_idx'),
        ),
        migrations.AddConstraint(
            model_name='decision',
            constraint=models.CheckConstraint(condition=models.Q(('observacion', ''), _negated=True), name='decision_observacion_no_vacia'),
        ),
        migrations.AddConstraint(
            model_name='procesoseleccion',
            constraint=models.CheckConstraint(condition=models.Q(('estado', 'RECHAZADO'), models.Q(('estado__in', ['LISTO_CONTRATACION', 'CONTRATADO']), ('etapa_actual', 'CONTRATACION')), models.Q(('estado', 'EN_CURSO'), ('etapa_actual__in', ['RRHH', 'PSICOLOGIA', 'SEGURIDAD'])), _connector='OR'), name='estado_coherente_con_etapa'),
        ),
        migrations.AddConstraint(
            model_name='seguimientoetapa',
            constraint=models.UniqueConstraint(condition=models.Q(('fin__isnull', True)), fields=('proceso',), name='un_seguimiento_abierto_por_proceso'),
        ),
        migrations.AddField(
            model_name='eventoseguridad',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_seguridad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='eventoseguridad',
            index=models.Index(fields=['tipo', 'fecha'], name='evento_tipo_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoseguridad',
            index=models.Index(fields=['ip', 'fecha'], name='evento_ip_fecha_idx'),
        ),
    ]
