# Generated by Django 6.0.8 on 2026-08-09 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0009_eventoseguridad_alter_perfil_rol_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='procesoseleccion',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('estado__in', ['EN_CURSO', 'LISTO_CONTRATACION'])), fields=('cedula',), name='una_postulacion_abierta_por_cedula'),
        ),
    ]
