# Generated by Django 6.0.8 on 2026-08-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0010_procesoseleccion_una_postulacion_abierta_por_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoseleccion',
            name='cedula_proceso_abierto',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
    ]
