# Generated by Django 6.0.8 on 2026-08-09 21:43

from django.db import migrations, models


def completar_claves_unicas(apps, schema_editor):
    Decision = apps.get_model("procesos", "Decision")
    SeguimientoEtapa = apps.get_model("procesos", "SeguimientoEtapa")

    for decision in Decision.objects.filter(vigente=True).iterator():
        decision.etapa_vigente = f"{decision.proceso_id}:{decision.etapa}"
        decision.save(update_fields=["etapa_vigente"])
    for seguimiento in SeguimientoEtapa.objects.filter(fin__isnull=True).iterator():
        seguimiento.proceso_en_curso = seguimiento.proceso_id
        seguimiento.save(update_fields=["proceso_en_curso"])


def vaciar_claves_unicas(apps, schema_editor):
    apps.get_model("procesos", "Decision").objects.update(etapa_vigente=None)
    apps.get_model("procesos", "SeguimientoEtapa").objects.update(proceso_en_curso=None)


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0011_procesoseleccion_cedula_proceso_abierto'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='etapa_vigente',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='seguimientoetapa',
            name='proceso_en_curso',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.RunPython(completar_claves_unicas, vaciar_claves_unicas),
    ]
